import {
  InputField,
  InputPassword,
  AppButton,
  IconPicker,
  ManyToMany,
  TypographyRenderer,
  YouTubeVideo,
  DateTimePicker,
  TimePicker,
  ThemeSwitcher,
  StringArrayInput,
  SearchAutocomplete,
  RangeSlider,
  RadioGroup,
  QuantitySelector,
  MultiSelectField,
  MultiImageCheckboxField,
  MultiCheckboxField,
  LoginCard,
  InputPriceRange,
  InputFile,
  InputEmoji,
  ImageRadioGroupField,
  Iframe,
  Gallery,
  Dropdown,
  AudioPicker,
  InputColor,
  InputCheckbox,
  InputDate,
  InputPhone,
  InputSwitch,
  Select,
  TextAreaField,
  InputOTP,
  DynamicSelect,
  DynamicMultiSelect,
} from "nishify";
export const formInput = {
  // Core Fields
  text: InputField,
  email: InputField,
  password: InputPassword,
  number: InputField,
  textarea: TextAreaField,
  switch: InputSwitch,
  select: Select,
  phone: InputPhone,
  date: InputDate,
  checkbox: InputCheckbox,
  otp: InputOTP,
  color: InputColor,
  submit: AppButton,
  typography: TypographyRenderer,

  // Specialized Fields & Components
  audio: AudioPicker,
  // brandLogos: BrandLogos,
  datetime: DateTimePicker,
  dropdown: Dropdown,
  "dynamic-select": DynamicSelect,
  dynamicSelect: DynamicSelect,
  "dynamic-multi-select": DynamicMultiSelect,
  dynamicMultiSelect: DynamicMultiSelect,
  "icon-picker": IconPicker,
  iconPicker: IconPicker,
  "many-to-many": ManyToMany,
  manyToMany: ManyToMany,
  gallery: Gallery,
  // address: GoogleAddressField,
  iframe: Iframe,
  imageRadio: ImageRadioGroupField,
  emoji: InputEmoji,
  file: InputFile,
  priceRange: InputPriceRange,
  loginCard: LoginCard,
  multiCheckbox: MultiCheckboxField,
  multiImageCheckbox: MultiImageCheckboxField,
  multiSelect: MultiSelectField,
  quantity: QuantitySelector,
  radio: RadioGroup,
  range: RangeSlider,
  autocomplete: SearchAutocomplete,
  stringArray: StringArrayInput,
  themeSwitcher: ThemeSwitcher,
  time: TimePicker,
  youtube: YouTubeVideo,

  // PascalCase versions for backward compatibility
  TextInput: InputField,
  TextArea: TextAreaField,
  Switch: InputSwitch,
  SelectField: Select,
  DynamicSelect: DynamicSelect,
  PhoneInput: InputPhone,
  DateInput: InputDate,
  CheckboxInput: InputCheckbox,
  // OTPInput: InputOtp,
  ColorInput: InputColor,
  MultiSelect: MultiSelectField,
  IconPicker: IconPicker,
  // GoogleAddress: GoogleAddressField,
};
