# be/client/airbnb/entities.py — entity DSL, the single source of truth.
# Airbnb-style stays client: listings, hosts, bookings, reviews, amenities.
# Sample data is scaffolding — swap "source" once a real API exists.

ENTITIES_ORDER = ["overview", "listing", "host", "booking", "review", "amenity"]

entities = {
    # Admin landing — OPTIONS returns `config` so the client's
    # airbnb-overview component renders instead of default-admin.
    "overview": {
        "source": "json",
        "fields": {"id": {"type": "int", "primary_key": True}},
        "ui": {},
        "config": [
            {
                "id": "airbnb-overview-1",
                "type": "airbnb-overview",
                "properties": {
                    "level": "base",
                    "type": "dynamic",
                    "action": [
                        {"key": "listings", "endpoint": "listing", "method": "GET",
                         "queryParams": {"size": 100}},
                        {"key": "bookings", "endpoint": "booking", "method": "GET",
                         "queryParams": {"size": 100, "sort": "check_in"}},
                        {"key": "hosts",    "endpoint": "host",    "method": "GET",
                         "queryParams": {"size": 100}},
                        {"key": "reviews",  "endpoint": "review",  "method": "GET",
                         "queryParams": {"size": 100}},
                    ],
                },
                "content": {},
            },
        ],
        "sample_data": [],
    },

    "listing": {
        "source": "json",
        "fields": {
            "id":        {"type": "int", "primary_key": True},
            "title":     {"type": "str", "required": True},
            "location":  {"type": "str"},
            "category":  {"type": "str", "default": "trending",
                          "options": ["beachfront", "cabins", "amazing-pools",
                                      "countryside", "city", "trending"]},
            "price":     {"type": "int", "required": True},
            "rating":    {"type": "float"},
            "reviews":   {"type": "int", "default": 0},
            "guests":    {"type": "int", "default": 2},
            "beds":      {"type": "int", "default": 1},
            "baths":     {"type": "int", "default": 1},
            "image":     {"type": "str"},
            "badge":     {"type": "str"},
            "host":      {"type": "str"},
            "available": {"type": "bool", "default": True},
        },
        "ui": {
            "table": {
                "columns": [
                    {"key": "id",       "label": "ID",       "sortable": True},
                    {"key": "title",    "label": "Listing",  "searchable": True},
                    {"key": "location", "label": "Location", "searchable": True},
                    {"key": "category", "label": "Category", "type": "badge",
                     "variants": {"beachfront": "default", "cabins": "secondary",
                                  "amazing-pools": "default", "countryside": "secondary",
                                  "city": "outline", "trending": "destructive"}},
                    {"key": "price",    "label": "Price/night", "sortable": True},
                    {"key": "rating",   "label": "Rating",   "sortable": True},
                    {"key": "available","label": "Live",     "type": "status"},
                ],
                "actions": ["open_form", "confirm_delete"],
            },
            "form": {
                "fields": [
                    {"name": "title",    "componentType": "TextInput",
                     "required": True, "colSpan": 2, "label": "Title"},
                    {"name": "location", "componentType": "TextInput", "label": "Location"},
                    {"name": "category", "componentType": "Select",
                     "options": ["beachfront", "cabins", "amazing-pools",
                                 "countryside", "city", "trending"],
                     "default": "trending", "label": "Category"},
                    {"name": "price",    "componentType": "NumberInput",
                     "required": True, "label": "Price / night"},
                    {"name": "rating",   "componentType": "NumberInput", "label": "Rating"},
                    {"name": "reviews",  "componentType": "NumberInput", "label": "Reviews"},
                    {"name": "guests",   "componentType": "NumberInput", "label": "Guests"},
                    {"name": "beds",     "componentType": "NumberInput", "label": "Beds"},
                    {"name": "baths",    "componentType": "NumberInput", "label": "Baths"},
                    {"name": "image",    "componentType": "TextInput",
                     "colSpan": 2, "label": "Image URL"},
                    {"name": "badge",    "componentType": "TextInput", "label": "Badge"},
                    {"name": "host",     "componentType": "TextInput", "label": "Host"},
                    {"name": "available","componentType": "Checkbox", "default": True,
                     "label": "Available"},
                ]
            },
        },
        "sample_data": [
            {"id": 1, "title": "Beachfront villa with infinity pool",
             "location": "Goa, India", "category": "beachfront",
             "price": 18400, "rating": 4.92, "reviews": 214,
             "guests": 8, "beds": 4, "baths": 4,
             "image": "https://picsum.photos/seed/airbnb-villa/640/420",
             "badge": "Guest favourite", "host": "Ananya", "available": True},
            {"id": 2, "title": "Cozy A-frame cabin in the pines",
             "location": "Manali, Himachal", "category": "cabins",
             "price": 6200, "rating": 4.85, "reviews": 189,
             "guests": 4, "beds": 2, "baths": 1,
             "image": "https://picsum.photos/seed/airbnb-cabin/640/420",
             "badge": "", "host": "Rohan", "available": True},
            {"id": 3, "title": "Cliffside house with plunge pool",
             "location": "Varkala, Kerala", "category": "amazing-pools",
             "price": 12800, "rating": 4.78, "reviews": 96,
             "guests": 6, "beds": 3, "baths": 3,
             "image": "https://picsum.photos/seed/airbnb-pool/640/420",
             "badge": "Rare find", "host": "Meera", "available": True},
            {"id": 4, "title": "Heritage haveli courtyard suite",
             "location": "Jaipur, Rajasthan", "category": "city",
             "price": 5400, "rating": 4.69, "reviews": 311,
             "guests": 3, "beds": 2, "baths": 2,
             "image": "https://picsum.photos/seed/airbnb-haveli/640/420",
             "badge": "", "host": "Vikram", "available": True},
            {"id": 5, "title": "Tea-estate bungalow with valley view",
             "location": "Munnar, Kerala", "category": "countryside",
             "price": 7900, "rating": 4.88, "reviews": 142,
             "guests": 5, "beds": 3, "baths": 2,
             "image": "https://picsum.photos/seed/airbnb-munnar/640/420",
             "badge": "Guest favourite", "host": "Sara", "available": True},
            {"id": 6, "title": "Skyline loft near Marine Drive",
             "location": "Mumbai, Maharashtra", "category": "city",
             "price": 9300, "rating": 4.61, "reviews": 88,
             "guests": 2, "beds": 1, "baths": 1,
             "image": "https://picsum.photos/seed/airbnb-loft/640/420",
             "badge": "", "host": "Arjun", "available": False},
            {"id": 7, "title": "Houseboat on the backwaters",
             "location": "Alleppey, Kerala", "category": "trending",
             "price": 11500, "rating": 4.95, "reviews": 264,
             "guests": 6, "beds": 3, "baths": 3,
             "image": "https://picsum.photos/seed/airbnb-boat/640/420",
             "badge": "Trending", "host": "Joseph", "available": True},
            {"id": 8, "title": "Beach shack steps from the sand",
             "location": "Palolem, Goa", "category": "beachfront",
             "price": 4500, "rating": 4.55, "reviews": 197,
             "guests": 2, "beds": 1, "baths": 1,
             "image": "https://picsum.photos/seed/airbnb-shack/640/420",
             "badge": "", "host": "Priya", "available": True},
        ],
    },

    "host": {
        "source": "json",
        "fields": {
            "id":            {"type": "int", "primary_key": True},
            "name":          {"type": "str", "required": True},
            "avatar":        {"type": "str"},
            "since":         {"type": "str"},
            "superhost":     {"type": "bool", "default": False},
            "response_rate": {"type": "int", "default": 90},
            "listings":      {"type": "int", "default": 1},
        },
        "ui": {
            "table": {
                "columns": [
                    {"key": "id",   "label": "ID",   "sortable": True},
                    {"key": "name", "label": "Host", "searchable": True},
                    {"key": "since","label": "Hosting since"},
                    {"key": "superhost", "label": "Superhost", "type": "status"},
                    {"key": "response_rate", "label": "Response %", "sortable": True},
                ],
                "actions": ["open_form", "confirm_delete"],
            },
        },
        "sample_data": [
            {"id": 1, "name": "Ananya", "since": "2018", "superhost": True,
             "response_rate": 99, "listings": 3},
            {"id": 2, "name": "Rohan",  "since": "2020", "superhost": False,
             "response_rate": 94, "listings": 1},
            {"id": 3, "name": "Meera",  "since": "2016", "superhost": True,
             "response_rate": 100, "listings": 2},
            {"id": 4, "name": "Joseph", "since": "2015", "superhost": True,
             "response_rate": 97, "listings": 4},
        ],
    },

    "booking": {
        "source": "json",
        "fields": {
            "id":        {"type": "int", "primary_key": True},
            "listing":   {"type": "str", "required": True},
            "guest":     {"type": "str", "required": True},
            "check_in":  {"type": "str"},
            "check_out": {"type": "str"},
            "guests":    {"type": "int", "default": 1},
            "total":     {"type": "int", "default": 0},
            "status":    {"type": "str", "default": "confirmed",
                          "options": ["confirmed", "pending", "cancelled", "completed"]},
        },
        "ui": {
            "table": {
                "columns": [
                    {"key": "id",       "label": "ID",      "sortable": True},
                    {"key": "listing",  "label": "Listing", "searchable": True},
                    {"key": "guest",    "label": "Guest",   "searchable": True},
                    {"key": "check_in", "label": "Check-in"},
                    {"key": "check_out","label": "Check-out"},
                    {"key": "total",    "label": "Total",   "sortable": True},
                    {"key": "status",   "label": "Status",  "type": "badge",
                     "variants": {"confirmed": "default", "pending": "secondary",
                                  "cancelled": "destructive", "completed": "outline"}},
                ],
                "actions": ["open_form", "confirm_delete"],
            },
            "form": {
                "fields": [
                    {"name": "listing",   "componentType": "TextInput",
                     "required": True, "colSpan": 2, "label": "Listing"},
                    {"name": "guest",     "componentType": "TextInput",
                     "required": True, "label": "Guest"},
                    {"name": "check_in",  "componentType": "TextInput", "label": "Check-in"},
                    {"name": "check_out", "componentType": "TextInput", "label": "Check-out"},
                    {"name": "guests",    "componentType": "NumberInput", "label": "Guests"},
                    {"name": "total",     "componentType": "NumberInput", "label": "Total"},
                    {"name": "status",    "componentType": "Select",
                     "options": ["confirmed", "pending", "cancelled", "completed"],
                     "default": "confirmed", "label": "Status"},
                ]
            },
        },
        "sample_data": [
            {"id": 1, "listing": "Beachfront villa with infinity pool",
             "guest": "Karan M.", "check_in": "2025-07-02", "check_out": "2025-07-06",
             "guests": 4, "total": 73600, "status": "confirmed"},
            {"id": 2, "listing": "Houseboat on the backwaters",
             "guest": "Elena R.", "check_in": "2025-07-11", "check_out": "2025-07-14",
             "guests": 2, "total": 34500, "status": "pending"},
            {"id": 3, "listing": "Tea-estate bungalow with valley view",
             "guest": "Dev S.", "check_in": "2025-06-18", "check_out": "2025-06-21",
             "guests": 5, "total": 23700, "status": "completed"},
            {"id": 4, "listing": "Cozy A-frame cabin in the pines",
             "guest": "Ishita P.", "check_in": "2025-07-20", "check_out": "2025-07-23",
             "guests": 2, "total": 18600, "status": "confirmed"},
        ],
    },

    "review": {
        "source": "json",
        "fields": {
            "id":      {"type": "int", "primary_key": True},
            "listing": {"type": "str", "required": True},
            "author":  {"type": "str"},
            "rating":  {"type": "int", "default": 5},
            "comment": {"type": "str"},
            "date":    {"type": "str"},
        },
        "ui": {
            "table": {
                "columns": [
                    {"key": "id",      "label": "ID",      "sortable": True},
                    {"key": "listing", "label": "Listing", "searchable": True},
                    {"key": "author",  "label": "Author",  "searchable": True},
                    {"key": "rating",  "label": "Rating",  "sortable": True},
                    {"key": "date",    "label": "Date"},
                ],
                "actions": ["open_form", "confirm_delete"],
            },
        },
        "sample_data": [
            {"id": 1, "listing": "Beachfront villa with infinity pool",
             "author": "Karan M.", "rating": 5,
             "comment": "Wake up to the waves — unbeatable.",
             "date": "2025-06-02"},
            {"id": 2, "listing": "Houseboat on the backwaters",
             "author": "Elena R.", "rating": 5,
             "comment": "Crew cooked us dinner on deck. Magical.",
             "date": "2025-05-19"},
            {"id": 3, "listing": "Cozy A-frame cabin in the pines",
             "author": "Ishita P.", "rating": 4,
             "comment": "Quiet, snowy, the fireplace is everything.",
             "date": "2025-04-30"},
        ],
    },

    "amenity": {
        "source": "json",
        "fields": {
            "id":   {"type": "int", "primary_key": True},
            "name": {"type": "str", "required": True},
            "icon": {"type": "str"},
        },
        "sample_data": [
            {"id": 1, "name": "Wifi",            "icon": "wifi"},
            {"id": 2, "name": "Pool",            "icon": "waves"},
            {"id": 3, "name": "Kitchen",         "icon": "chef-hat"},
            {"id": 4, "name": "Free parking",    "icon": "car"},
            {"id": 5, "name": "Air conditioning","icon": "snowflake"},
            {"id": 6, "name": "Pet friendly",    "icon": "paw-print"},
        ],
    },
}
